### ISSUE TITLE
Classes exported from modules are visible in the root namespace

### ISSUE THREAD

**Issue by olofson** [olofson/eel#120]
Classes exported from native modules (via eel_export_class()) show up in the root namespace (via the VM class registry) as well as the module exports table, which can result in confusion and conflicts.

The compiler should probably not use the class registry for lookups at all. The value types and builtin classes might be an exception, but there are various other ways of dealing with those.

**Comment by chille** [comment]
Was there some trouble with the issue auto close from the commit message, or is issue supposed to still be open?

**Comment by olofson** [comment]
Yeah, sorry about that. :-D Was planning on finishing that project up "any day now," so I haven't bothered merging individual commits to master - but I got distracted, and during February, I'm doing an album (https://www.rpmchallenge.com/) so not much happening there right now.
